"""align schema with models

Revision ID: 018d02f230de
Revises: 52ed405e2963
Create Date: 2026-01-04 15:40:21.717733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '018d02f230de'
down_revision: Union[str, Sequence[str], None] = '52ed405e2963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_snapshots_channel_id', 'analytics_snapshots', ['channel_id'], unique=False)
    op.create_index('idx_channels_user_id', 'channels', ['user_id'], unique=False)
    op.alter_column('chat_sessions', 'tools_used',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('idx_chat_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_video_channel_id', 'video_snapshots', ['channel_id'], unique=False)
    op.alter_column('weekly_insights', 'wins',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weekly_insights', 'losses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weekly_insights', 'next_actions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('idx_weekly_channel_id', 'weekly_insights', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weekly_channel_id', table_name='weekly_insights')
    op.alter_column('weekly_insights', 'next_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weekly_insights', 'losses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weekly_insights', 'wins',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_video_channel_id', table_name='video_snapshots')
    op.drop_index('idx_chat_user_id', table_name='chat_sessions')
    op.alter_column('chat_sessions', 'tools_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_channels_user_id', table_name='channels')
    op.drop_index('idx_snapshots_channel_id', table_name='analytics_snapshots')
    # ### end Alembic commands ###
