"""Add OAuth token fields to channels

Revision ID: 82a9642b00c1
Revises: 018d02f230de
Create Date: 2026-01-16 21:37:57.060823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82a9642b00c1'
down_revision: Union[str, Sequence[str], None] = '018d02f230de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_channels_youtube_id', 'channels', ['youtube_channel_id'], unique=False)
    op.create_unique_constraint('uq_user_youtube_channel', 'channels', ['user_id', 'youtube_channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_youtube_channel', 'channels', type_='unique')
    op.drop_index('idx_channels_youtube_id', table_name='channels')
    op.alter_column('channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
